name: DooN_Build_v4_Clean
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          sudo git clone --recursive https://github.com/theos/theos.git /opt/theos
          git clone https://github.com/theos/sdks.git /opt/theos/sdks
          sudo chown -R $(id -u):$(id -g) /opt/theos

      - name: Build Dylib
        run: |
          export THEOS=/opt/theos
          make package FINAL_PACKAGE=1
          
      - name: Upload Result âœ…
        uses: actions/upload-artifact@v4
        with:
          name: DooN-Dylib
          path: .theos/obj/debug/*.dylib