name: DooN_Wizard_Final_Fix
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos & ldid
        run: |
          brew install ldid
          sudo rm -rf /opt/theos
          sudo git clone --recursive https://github.com/theos/theos.git /opt/theos
          sudo git clone https://github.com/theos/sdks.git /tmp/sdks
          sudo mv /tmp/sdks/iPhoneOS14.5.sdk /opt/theos/sdks/
          sudo chown -R $(id -u):$(id -g) /opt/theos

      - name: Build Dylib
        run: |
          export THEOS=/opt/theos
          # تعديل سطر الـ make لحل مشاكل armv7 و keyWindow
          make FINAL_PACKAGE=1 ARCHS="arm64" ADDITIONAL_CFLAGS="-Wno-deprecated-declarations"
          
      - name: Upload Result ✅
        uses: actions/upload-artifact@v4
        with:
          name: DooN-Dylib-Ready
          # استخدام المسار الشامل لضمان إيجاد الملف مهما كان مكانه
          path: .theos/obj/**/*.dylib