name: DooN_Build_Clean
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos & SDK
        run: |
          # تحميل الثيوس والـ SDK في مسار المستخدم لتجنب مشاكل الصلاحيات
          git clone --recursive https://github.com/theos/theos.git ~/theos
          git clone https://github.com/theos/sdks.git ~/theos/sdks
          
      - name: Build Dylib
        run: |
          # تعريف المسار الجديد اللي حملنا فيه
          export THEOS=~/theos
          # تنفيذ أمر البناء المباشر
          make package FINAL_PACKAGE=1
          
      - name: Upload ✅
        uses: actions/upload-artifact@v4
        with:
          name: DooN-Dylib
          path: .theos/obj/debug/*.dylib